[project]
name = "notte-mcp"
version = "1.4.4.dev"
description = "The MCP server for Notte"
readme = "README.md"
authors = [
    { name = "Notte Team ", email = "hello@notte.cc" }
]
packages = [
    { include = "notte_mcp", from = "src" },
]


requires-python = ">=3.13"
dependencies = [
    "notte-sdk",
    "fastmcp",
    "python-dotenv>=1.1.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
